project:
  title: "cityseer-examples"
  output-dir: ./output
  type: website
website:
  title: Cityseer Guide
  description: A guide and some examples of how to use cityseer.
  page-navigation: true
  repo-url: https://github.com/benchmark-urbanism/cityseer-examples
  navbar:
    search: true
  search:
    location: navbar
    type: overlay
  sidebar:
    logo: ./assets/round_logo.png
    style: "docked"
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Overview
      - href: recipes/cookbook.qmd
        text: Cookbook
      - href: data/datasets.qmd
        text: Data

format:
  html:
    theme: simplex
    toc: true
    mermaid:
      theme: dark
    highlight-style: breezedark
    css: ./custom-style.css
