---
title: Datasets
editor:
  render-on-save: true
---

The datasets used from the recipes are provided for reproducibility and further exploration per the following links. Please refer to the respective sources for the most up-to-date versions. Please use the datasets in accordance with the source licenses (these should be open, but please check) and be sure to cite the original authors of the data.

Dataset preprocessing is done per the [ua-dataset-madrid](https://github.com/songololo/ua-dataset-madrid) repository, which is intended to be a source for openly reproducible urban analytics data for reproducible papers, workflows, and tutorials.

## Neighbourhoods

[Shapefile](./madrid_nbhds/madrid_nbhds.zip)

[GeoPackage](./madrid_nbhds/madrid_nbhds.gpkg)

[Source](https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=760e5eb0d73a7710VgnVCM2000001f4a900aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default)

[License](https://datos.madrid.es/egob/catalogo/aviso-legal)

Origin of the data: Madrid City Council (or, where appropriate, administrative body, body or entity in question)

Description: Delimitation of the 131 neighborhoods of the municipality of Madrid. The names and codes of each neighborhood and the districts to which they belong are indicated. The initial delimitation corresponds to the territorial restructuring of 1987.

## Blocks

[GeoPackage](./madrid_blocks/madrid_blocks.gpkg)

[Source](https://land.copernicus.eu/en/products/urban-atlas/urban-atlas-2018)

[License](https://land.copernicus.eu/en/data-policy)

The Copernicus land monitoring products and services are made available on a principle of full, open and free access, as established by the Commission Delegated Regulation (EU) No 1159/2013 of 12 July 2013.
Free, full and open access to the products and services of the Copernicus Land Monitoring Service is made on the conditions that:

1. When distributing or communicating Copernicus Land Monitoring Service products and services (data, software scripts, web services, user and methodological documentation and similar) to the public, users shall inform the public of the source of these products and services.
2. Where the Copernicus Land Monitoring Service products and services have been adapted or modified by the user, the user shall clearly state this.
3. Users shall make sure not to convey the impression to the public that the user's activities are officially endorsed by the European Union.

Urban Atlas Land Cover/Land Use 2018 (vector), Europe, 6-yearly. European Union's Copernicus Land Monitoring Service information, [https://land.copernicus.eu/en/products/urban-atlas/urban-atlas-2018](https://land.copernicus.eu/en/products/urban-atlas/urban-atlas-2018). [https://doi.org/10.2909/fb4dffa1-6ceb-4cc0-8372-1ed354c285e6](https://doi.org/10.2909/fb4dffa1-6ceb-4cc0-8372-1ed354c285e6) (Accessed on DD.MM.YYYY)

## Premises

[GeoPackage](./madrid_premises/madrid_premises.gpkg)

[CSV](./madrid_premises/madrid_premises.csv)

[Source](https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=66665cde99be2410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default)

[License](https://datos.madrid.es/egob/catalogo/aviso-legal)

Origin of the data: Madrid City Council (or, where appropriate, administrative body, body or entity in question)

Description: Microdata file of the census of premises and activities of the Madrid City Council, classified according to their type of access (street door or grouped), situation (open, closed...) and indication of the economic activity exercised and the hospitality and restaurant terraces that appear registered in said census.

Preprocessing performed per: [https://github.com/songololo/ua-dataset-madrid](https://github.com/songololo/ua-dataset-madrid).

## Overture Maps Buildings

[GeoPackage](./madrid_buildings/madrid_bldgs.gpkg)

[Source](https://docs.overturemaps.org/guides/buildings/#14/32.58453/-117.05154/0/60)

[License](https://docs.overturemaps.org/attribution/)

License for theme: ODbL

- © OpenStreetMap contributors. Available under the Open Database License.
- Esri Community Maps contributors. Available under CC BY 4.0.
- Global ML Building Footprints. Licensed by Microsoft under the Open Database License.
- Google Open Buildings. Available under CC BY 4.0.
- USGS 3D Elevation Program Digital Elevation Program.
- Qian Shi, et al. A First High-quality Vector Data of Buildings in East Asian Countries Based on a Comprehensive Large-scale Mapping Framework. Zenodo, 22 July 2023, doi:10.5281/zenodo.8174931. Available under CC BY 4.0.

## Overture Maps Infrastructure

[GeoPackage](./madrid_infrastucture/madrid_infrast.gpkg)

[Source](https://docs.overturemaps.org/guides/base/#14/32.58453/-117.05154/0/60)

[License](https://docs.overturemaps.org/attribution/)

License for theme: ODbL

- © OpenStreetMap contributors. Available under the Open Database License.
- Data from the Daylight Map Distribution
- ESA WorldCover. Available under CC BY 4.0 DEED.
- Data products from ETOPO1. Available under Open Data Commons Public Domain Dedication and License.
- Data from GLOBathy. Available under CC0 1.0 (assumed).

## Streets

[GeoPackage](./madrid_streets/street_network.gpkg)

[Source](https://datos.comunidad.madrid/dataset/spacm_callescm)

[License](https://creativecommons.org/licenses/by/4.0/)

Origin of the data: Madrid City Council (or, where appropriate, administrative body, body or entity in question)

Description: Set of roads officially approved by the municipalities of the Community of Madrid, ordered by different characteristics.

Preprocessing and manual cleaning performed per: [https://github.com/songololo/ua-dataset-madrid](https://github.com/songololo/ua-dataset-madrid).

## Census

[GeoPackage](./madrid_census/eu_stat_clipped.gpkg)

[Source](https://ec.europa.eu/eurostat/web/gisco/geodata/population-distribution/geostat)

[License](https://ec.europa.eu/eurostat/web/main/help/copyright-notice)

Copyright European Union 2025 - The source needs to be indicated and when re-use involves modifications to the data or text, this must be stated clearly to the end user of the information. For further information refer to [https://ec.europa.eu/eurostat/web/main/help/copyright-notice](https://ec.europa.eu/eurostat/web/main/help/copyright-notice).

| Code    | Description                          |
| ------- | ------------------------------------ |
| T       | Total population                     |
| M       | Male population                      |
| F       | Female population                    |
| Y_LT15  | Age under 15 years                   |
| Y_1564  | Age 15 to 64 years                   |
| Y_GE65  | Age 65+ years                        |
| EMP     | Employed persons                     |
| NAT     | Born in reporting country            |
| EU_OTH  | Born in other EU Member State        |
| OTH     | Born elsewhere                       |
| SAME    | Residence unchanged in past year     |
| CHG_IN  | Moved within reporting country       |
| CHG_OUT | Moved from outside reporting country |
