---
editor:
  render-on-save: true
---

This section provides some basic examples on the usage of Python and computational notebooks if you're new to programming or urban analytics. These are high-level examples to give a basic indication of how these tools might typically be used.

### Topics Covered

1. **Notebooks**: Learn what computational notebooks are and how to use them effectively. [Notebooks](1_notebooks.qmd)
2. **Python 101**: Get familiar with Python basics, including variables, data types, and simple operations. [Python 101](2_basics.qmd)
3. **Spatial Data**: Explore spatial data and basic operations for urban analysis. [Spatial Data](3_spatial.qmd)
4. **Pandas**: Dive into data manipulation and analysis using the pandas library. [Pandas](4_pandas.qmd)
5. **Urban Morphology**: Analyse urban forms and patterns with the `momepy` library. [Urban Morphology](5_momepy.qmd)
6. **OpenStreetMap Data**: Work with OpenStreetMap data using the `osmnx` library. [OpenStreetMap Data](6_osmnx.qmd)
7. **Cityseer**: Discover the `cityseer` library and its applications in urban analysis. [Cityseer](7_cityseer.qmd)
8. **Data Science Workflows**: Learn about workflows for data science projects. [Data Science Workflows](8_data_science.ipynb)
9. **Modelling and Analysis**: Explore modelling techniques and analytical methods. [Modeling and Analysis](9_models.ipynb)
