on:
  push:
    branches: main
name: Render and Publish
# you need these permissions to publish to GitHub pages
permissions:
  contents: write
  pages: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      # quarto doesn't seem to find PDM installs so export to requirements and install manually below
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: "3.11"
          cache: true
      - run: pdm export -f requirements -o requirements.txt
      - uses: actions/setup-python@v5
        name: Setup Python
        with:
          python-version: "3.11"
      - name: Install
        run: pip install -r requirements.txt
      # See more at https://github.com/quarto-dev/quarto-actions/blob/main/examples/example-03-dependencies.md
      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
